name: drivetools

services:
  nginx:
    container_name: 'nginx'
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/templates/nginx.conf.template
      - /etc/letsencrypt/ssl-dhparams.pem:/etc/letsencrypt/ssl-dhparams.pem
      - /etc/letsencrypt/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - /etc/letsencrypt/live/${DOMAIN}/fullchain.pem:/etc/letsencrypt/live/${DOMAIN}/fullchain.pem
      - /etc/letsencrypt/live/${DOMAIN}/privkey.pem:/etc/letsencrypt/live/${DOMAIN}/privkey.pem
    networks:
      - drivetools-network
    restart: always
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
      DOMAIN: ${DOMAIN}
      CLIENT_PORT: ${CLIENT_PORT}

  client:
    container_name: ${CLIENT_DOMAIN}
    build:
    context: ../../${REPO_NAME_BASE}.${CLIENT_DOMAIN}
    dockerfile: ./docker/Dockerfile.client
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    restart: always
    networks:
      - drivetools-network
    environment:
      REPO_NAME_BASE: ${REPO_NAME_BASE}
      CLIENT_DOMAIN: ${CLIENT_DOMAIN}
      CLIENT_PORT: ${CLIENT_PORT}

networks:
  drivetools-network:
    driver: bridge